#!/usr/bin/env bash
# AIKEY-l4qkxonqry2b4gj7bsrkqpryiy
# bootstrap.sh — Build `run` and generate shim scripts in tools/.
#
# Run this once after cloning, or whenever you add a new crate to the workspace.
# Re-running is safe: existing shims are overwritten in place.
#
# Usage:
#   ./bootstrap.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="$SCRIPT_DIR/tools"

# Cursor agent shells often set CARGO_TARGET_DIR to a sandbox cache, which
# would place artifacts outside ./target/ and break shims that expect
# target/debug/run. Unset so cargo uses the workspace default layout.
# (See docs/design/cursor-cargo-target-dir.md.)
if [[ -n "${CURSOR_AGENT:-}" || -n "${CURSOR_TRACE_ID:-}" ]]; then
  unset CARGO_TARGET_DIR
elif [[ "${CARGO_TARGET_DIR:-}" == *cursor-sandbox-cache* ]]; then
  unset CARGO_TARGET_DIR
fi

# ── 1. Build the auto-recompile runner ───────────────────────────────────────
echo "bootstrap: building run …"
cargo build -p run --manifest-path "$SCRIPT_DIR/Cargo.toml"
echo "bootstrap: done — target/debug/run is ready"
echo ""

# ── 2. Generate shims ────────────────────────────────────────────────────────
# One shim per crate binary. Each shim auto-rebuilds its binary when source
# changes, then execs it. Add new crate names to this list as they are created.
CRATES=(
  agents-zip
  bump-npm-version
  cargo-unlock
  clean-build-dirs
  clean-build-dirs-async
  cleanse
  copy-feed-files
  forfiles
  freeze
  inject-key
  listrepos
  retry-forfiles
  scaffold-repo
)

SHIM_TEMPLATE='#!/usr/bin/env bash
# Auto-generated by bootstrap.sh — do not edit by hand.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "$SCRIPT_DIR/../target/debug/run" "$(basename "$0")" "$@"
'

echo "bootstrap: generating shims in tools/ …"
for crate in "${CRATES[@]}"; do
  dest="$TOOLS_DIR/$crate"
  printf '%s' "$SHIM_TEMPLATE" > "$dest"
  chmod +x "$dest"
  echo "  generated  $dest"
done
echo ""
echo "bootstrap: ${#CRATES[@]} shims ready. Add tools/ to PATH or invoke directly:"
echo "  export PATH=\"\$PATH:$TOOLS_DIR\""
