[package]
name = "git-recurse"
version.workspace = true
edition.workspace = true

[[bin]]
name = "git-recurse"
path = "src/main.rs"

[dependencies]
anyhow     = { workspace = true }
clap       = { workspace = true, features = ["env"] }
repoutils  = { workspace = true }
serde_json = { workspace = true }
