#!/bin/sh
# AIKEY-l4qkxonqry2b4gj7bsrkqpryiy
# AUTO-GENERATED by gen.py (depth=2) — edit gen.py, not this file.
. "$(dirname $0)/bootstrap.sh"
ls -d */*/ | "$RUN" forfiles -C '^' '^' sh -c 'echo >> .gitignore; echo target >> .gitignore; echo node_modules >> .gitignore; echo .DS_Store >> .gitignore'
sh $(dirname $0)/sortallignores.sh
