#!/bin/sh
# AIKEY-l4qkxonqry2b4gj7bsrkqpryiy
# AUTO-GENERATED by gen.py (depth=2) — edit gen.py, not this file.
. "$(dirname $0)/bootstrap.sh"
ls -d */*/ | "$RUN" retry-forfiles -C '^' '^' sh -c 'git add -A; git commit -m update'
