#!/bin/sh
# AIKEY-l4qkxonqry2b4gj7bsrkqpryiy
# AUTO-GENERATED by gen.py (max_depth=3) — edit gen.py, not this file.
. "$(dirname $0)/bootstrap.sh"
"$RUN" listrepos --max-depth 3 --git --cargo --clean-lockfiles-only | "$RUN" forfiles -C '^' '^' sh -c 'cargo fmt; git add -A; git commit -m fmt'
