#!/usr/bin/env python3
"""
Generate *all[n].sh scripts for batch operations over nested directories.

Usage:
    python3 gen.py [max_depth]   # default 3

Generated names:
    stem.sh       max depth 1  (repos at depths 1 only)
    stem2.sh      max depth 2  (repos at depths 1..2)
    stemN.sh      max depth N  (repos at depths 1..N)

Discovery uses the listrepos binary (max-depth cumulative, property filters).
"""

import os
import stat
import sys

AIKEY = "AIKEY-l4qkxonqry2b4gj7bsrkqpryiy"

# (stem, use_retry_forfiles, command, postfix_lines, exclude_mode, all_remotes)
# exclude_mode controls listrepos filters:
#   "none"  — all directories up to max depth
#   "git"   — git repo roots only (directory contains `.git`)
#   "cargo" — git repo roots with Cargo.toml and clean lockfile-only trees
# all_remotes: wrap pull/push in a loop over `git remote` (commitandpushall: push only)
OPERATIONS = [
    ("pullall",
     True,
     "git pull --no-rebase",
     [],
     "git",
     True),
    ("pushall",
     True,
     "git push",
     [],
     "git",
     True),
    ("commitall",
     True,
     "sh -c 'git add -A; git commit -m update'",
     [],
     "git",
     False),
    ("commitandpushall",
     True,
     "sh -c 'git add -A; git commit -m update'",
     [],
     "git",
     "push"),
    ("fmtallcargo",
     False,
     "sh -c 'cargo fmt; git add -A; git commit -m fmt'",
     [],
     "cargo",
     False),
    ("updateallcargo",
     False,
     "sh -c 'cargo update; git add -A; git commit -m update'",
     [],
     "cargo",
     False),
    ("upgradeallcargo",
     False,
     "sh -c 'cargo upgrade; git add -A; git commit -m upgrade'",
     [],
     "cargo",
     False),
    ("codeall",
     False,
     "code .",
     [],
     "none",
     False),
    ("sortallignores",
     False,
     "sh -c '(cat .gitignore || true) | sort | uniq > .gitignore.2; mv .gitignore.2 .gitignore'",
     [],
     "none",
     False),
    ("addignores",
     False,
     "sh -c 'echo >> .gitignore; echo target >> .gitignore; echo node_modules >> .gitignore; echo .DS_Store >> .gitignore'",
     ["sh $(dirname $0)/sortallignores.sh"],
     "none",
     False),
]


def listrepos_cmd(max_depth: int, exclude_mode: str) -> str:
    flags = [f'--max-depth {max_depth}']
    if exclude_mode == "git":
        flags.append("--git")
    elif exclude_mode == "cargo":
        flags.extend(["--git", "--cargo", "--clean-lockfiles-only"])
    elif exclude_mode != "none":
        raise ValueError(f"unknown exclude_mode: {exclude_mode!r}")
    return '"$RUN" listrepos ' + " ".join(flags)


def git_foreach_remote(pull_or_push: str) -> str:
    """Shell body: run git pull/push for every configured remote (no-op if none)."""
    if pull_or_push == "pull":
        inner = 'for r in $(git remote); do git pull --no-rebase "$r" || exit 1; done'
    elif pull_or_push == "push":
        inner = 'for r in $(git remote); do git push "$r" || exit 1; done'
    else:
        raise ValueError(f"unknown pull_or_push: {pull_or_push!r}")
    return f"sh -c '{inner}'"


def resolve_command(cmd: str, all_remotes) -> str:
    if all_remotes is True:
        if cmd == "git pull --no-rebase":
            return git_foreach_remote("pull")
        if cmd == "git push":
            return git_foreach_remote("push")
        raise ValueError(f"all_remotes not supported for command: {cmd!r}")
    if all_remotes == "push":
        inner = (
            "git add -A; git commit -m update; "
            "for r in $(git remote); do git push \"$r\" || exit 1; done"
        )
        return f"sh -c '{inner}'"
    if all_remotes:
        raise ValueError(f"invalid all_remotes: {all_remotes!r}")
    return cmd


def script_name(stem: str, max_depth: int) -> str:
    suffix = "" if max_depth == 1 else str(max_depth)
    return f"{stem}{suffix}.sh"


def render(
    stem: str,
    retry: bool,
    cmd: str,
    postfix: list[str],
    max_depth: int,
    *,
    exclude_mode: str,
    all_remotes,
) -> str:
    runner = "retry-forfiles" if retry else "forfiles"
    discover = listrepos_cmd(max_depth, exclude_mode)
    command = resolve_command(cmd, all_remotes)
    header = [
        "#!/bin/sh",
        f"# {AIKEY}",
        f"# AUTO-GENERATED by gen.py (max_depth={max_depth}) — edit gen.py, not this file.",
        '. "$(dirname $0)/bootstrap.sh"',
    ]
    body = [
        f'{discover} | "$RUN" {runner} -C \'^\' \'^\' {command}',
    ]
    return "\n".join(header + body + postfix) + "\n"


def generate(max_depth: int, out_dir: str) -> None:
    for stem, retry, cmd, postfix, exclude_mode, all_remotes in OPERATIONS:
        for depth in range(1, max_depth + 1):
            name = script_name(stem, depth)
            path = os.path.join(out_dir, name)
            content = render(
                stem,
                retry,
                cmd,
                postfix,
                depth,
                exclude_mode=exclude_mode,
                all_remotes=all_remotes,
            )
            with open(path, "w") as f:
                f.write(content)
            os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            print(f"  wrote {name}")


if __name__ == "__main__":
    max_depth = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    out_dir = os.path.dirname(os.path.abspath(__file__))
    print(f"Generating max depths 1–{max_depth} in {out_dir}")
    generate(max_depth, out_dir)
    print("Done.")
