#!/usr/bin/env python3
"""
Generate *all[n].sh scripts for arbitrary directory depths.

Usage:
    python3 gen.py [max_depth]   # default 3

Generated names:
    stem.sh       depth 1  (ls)
    stem2.sh      depth 2  (ls -d */*/)
    stemN.sh      depth N  (ls -d */.../N)
"""

import os
import stat
import sys

AIKEY = "AIKEY-l4qkxonqry2b4gj7bsrkqpryiy"

# Lockfile basenames allowed when deciding if a repo is "clean enough" for
# fmt/update/upgrade batch passes (see pass_a_cargo_clean_excludes_sh).
LOCKFILE_BASENAMES = (
    "Cargo.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
)

# (stem, use_retry_forfiles, command, postfix_lines, exclude_mode)
# exclude_mode:
#   "none"     — single forfiles pass (no exclude-from).
#   "git"      — two passes; pass A excludes dirs that are not git work trees.
#   "cargo"    — two passes; pass A excludes non-git dirs and dirty non-lockfile
#                trees (see LOCKFILE_BASENAMES).
OPERATIONS = [
    ("pullall",
     True,
     "git pull --no-rebase",
     [],
     "git"),
    ("pushall",
     True,
     "git push",
     [],
     "git"),
    ("commitall",
     True,
     "sh -c 'git add -A; git commit -m update'",
     [],
     "git"),
    ("commitandpushall",
     True,
     "sh -c 'git add -A; git commit -m update; git push'",
     [],
     "git"),
    ("fmtallcargo",
     False,
     "sh -c 'cargo fmt; git add -A; git commit -m fmt'",
     [],
     "cargo"),
    ("updateallcargo",
     False,
     "sh -c 'cargo update; git add -A; git commit -m update'",
     [],
     "cargo"),
    ("upgradeallcargo",
     False,
     "sh -c 'cargo upgrade; git add -A; git commit -m upgrade'",
     [],
     "cargo"),
    ("codeall",
     False,
     "code .",
     [],
     "none"),
    ("sortallignores",
     False,
     "sh -c '(cat .gitignore || true) | sort | uniq > .gitignore.2; mv .gitignore.2 .gitignore'",
     [],
     "none"),
    ("addignores",
     False,
     "sh -c 'echo >> .gitignore; echo target >> .gitignore; echo node_modules >> .gitignore; echo .DS_Store >> .gitignore'",
     ["sh $(dirname $0)/sortallignores.sh"],
     "none"),
]


def lockfile_case_arm() -> str:
    return "|".join(f"*/{n}|{n}" for n in LOCKFILE_BASENAMES)


def pass_a_git_only_excludes_sh() -> str:
    """Pass A for plain git batch scripts: exclude non-work-tree dirs only."""
    inner = (
        "git rev-parse --is-inside-work-tree >/dev/null 2>&1 "
        "|| { printf %s\\n ^; exit 0; };"
        "exit 0"
    )
    return f"sh -c '{inner}'"


def pass_a_cargo_clean_excludes_sh() -> str:
    """Pass A for cargo batch scripts: exclude non-git dirs and dirty non-lockfile trees."""
    arm = lockfile_case_arm()
    inner = (
        "git rev-parse --is-inside-work-tree >/dev/null 2>&1 "
        "|| { printf %s\\n ^; exit 0; };"
        "t=$(mktemp);"
        "git diff --name-only HEAD >\"$t\" 2>/dev/null || true;"
        "git ls-files --others --exclude-standard >>\"$t\" 2>/dev/null || true;"
        "bad=;"
        "while IFS= read -r f; do "
        "[ -z \"$f\" ] && continue;"
        "case \"$f\" in "
        f"{arm}) ;; "
        "*) bad=1; break;; "
        "esac; "
        "done <\"$t\";"
        "rm -f \"$t\";"
        "[ -n \"$bad\" ] && printf %s\\n ^;"
        "exit 0"
    )
    return f"sh -c '{inner}'"


def depth_ls(n: int) -> str:
    if n == 1:
        return "ls"
    return "ls -d " + "*/" * n


def script_name(stem: str, depth: int) -> str:
    suffix = "" if depth == 1 else str(depth)
    return f"{stem}{suffix}.sh"


def render(
    stem: str,
    retry: bool,
    cmd: str,
    postfix: list[str],
    depth: int,
    *,
    exclude_mode: str,
) -> str:
    runner = "retry-forfiles" if retry else "forfiles"
    ls = depth_ls(depth)
    header = [
        "#!/bin/sh",
        f"# {AIKEY}",
        f"# AUTO-GENERATED by gen.py (depth={depth}) — edit gen.py, not this file.",
        '. "$(dirname $0)/bootstrap.sh"',
    ]
    if exclude_mode == "git":
        collect = pass_a_git_only_excludes_sh()
        body = [
            'EX=$(mktemp)',
            'trap \'rm -f "$EX"\' EXIT',
            f'{ls} | "$RUN" {runner} -C \'^\' \'^\' {collect} >>"$EX" || true',
            f'{ls} | "$RUN" {runner} --exclude-from "$EX" -C \'^\' \'^\' {cmd}',
        ]
    elif exclude_mode == "cargo":
        collect = pass_a_cargo_clean_excludes_sh()
        body = [
            'EX=$(mktemp)',
            'trap \'rm -f "$EX"\' EXIT',
            f'{ls} | "$RUN" {runner} -C \'^\' \'^\' {collect} >>"$EX" || true',
            f'{ls} | "$RUN" {runner} --exclude-from "$EX" -C \'^\' \'^\' {cmd}',
        ]
    elif exclude_mode == "none":
        body = [f'{ls} | "$RUN" {runner} -C \'^\' \'^\' {cmd}']
    else:
        raise ValueError(f"unknown exclude_mode: {exclude_mode!r}")
    return "\n".join(header + body + postfix) + "\n"


def generate(max_depth: int, out_dir: str) -> None:
    for stem, retry, cmd, postfix, exclude_mode in OPERATIONS:
        for depth in range(1, max_depth + 1):
            name = script_name(stem, depth)
            path = os.path.join(out_dir, name)
            content = render(
                stem,
                retry,
                cmd,
                postfix,
                depth,
                exclude_mode=exclude_mode,
            )
            with open(path, "w") as f:
                f.write(content)
            os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            print(f"  wrote {name}")


if __name__ == "__main__":
    max_depth = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    out_dir = os.path.dirname(os.path.abspath(__file__))
    print(f"Generating depths 1–{max_depth} in {out_dir}")
    generate(max_depth, out_dir)
    print("Done.")
