#!/bin/sh
# AIKEY-l4qkxonqry2b4gj7bsrkqpryiy
# AUTO-GENERATED by gen.py (max_depth=1) — edit gen.py, not this file.
. "$(dirname $0)/bootstrap.sh"
"$RUN" listrepos --max-depth 1 --git | "$RUN" retry-forfiles -C '^' '^' sh -c 'for r in $(git remote); do git pull --no-rebase "$r" || exit 1; done'
