#!/bin/sh
# AIKEY-l4qkxonqry2b4gj7bsrkqpryiy
# AUTO-GENERATED by gen.py (depth=2) — edit gen.py, not this file.
. "$(dirname $0)/bootstrap.sh"
EX=$(mktemp)
trap 'rm -f "$EX"' EXIT
ls -d */*/ | "$RUN" retry-forfiles -C '^' '^' sh -c 'git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { printf %s\n ^; exit 0; };exit 0' >>"$EX" || true
ls -d */*/ | "$RUN" retry-forfiles --exclude-from "$EX" -C '^' '^' git push
