#!/bin/sh
# AIKEY-l4qkxonqry2b4gj7bsrkqpryiy
# AUTO-GENERATED by gen.py (depth=2) — edit gen.py, not this file.
. "$(dirname $0)/bootstrap.sh"
ls -d */*/ | "$RUN" forfiles -C '^' '^' sh -c '(cat .gitignore || true) | sort | uniq > .gitignore.2; mv .gitignore.2 .gitignore'
