#!/bin/sh
# AIKEY-l4qkxonqry2b4gj7bsrkqpryiy
# AUTO-GENERATED by gen.py (depth=1) — edit gen.py, not this file.
. "$(dirname $0)/bootstrap.sh"
ls | "$RUN" forfiles -C '^' '^' sh -c 'cargo update; git add -A; git commit -m update'
