// @ts-nocheck
// Generated by gen-agent-sandbox — do not edit by hand.
import * as fs from "node:fs";
import { spawnSync } from "node:child_process";

const POLICY = <<<POLICY_JSON>>>;

function parseCommand(cmd: string): string {
  const argv = POLICY.shellParserArgv;
  if (!argv || argv.length === 0) return cmd;
  const bin = argv[0];
  const args = argv.slice(1);
  const r = spawnSync(bin, args, { input: cmd, encoding: "utf8", maxBuffer: 10 * 1024 * 1024 });
  if (r.status !== 0 || typeof r.stdout !== "string") return cmd;
  const out = r.stdout.trim();
  return out.length > 0 ? out : cmd;
}

function isBashTool(name: string | undefined): boolean {
  if (!name) return false;
  return POLICY.bashToolNames.includes(name);
}

function denyReason(cmd: string): string | null {
  for (const s of POLICY.denySubstrings) {
    if (s && cmd.includes(s)) return `Denied: command contains blocked substring: ${s}`;
  }
  for (const src of POLICY.denyRegexes) {
    if (!src) continue;
    try {
      const re = new RegExp(src);
      if (re.test(cmd)) return `Denied: command matches blocked pattern: ${src}`;
    } catch {
      continue;
    }
  }
  return null;
}

function applyConnection(cmd: string): string {
  const p = POLICY.connectionScriptPath;
  const triggers = POLICY.connectionScriptTriggers;
  if (!p || triggers.length === 0) return cmd;
  for (const t of triggers) {
    if (t && cmd.includes(t)) return `${p} ${cmd}`;
  }
  return cmd;
}

function applyPrefix(cmd: string): string {
  const pre = POLICY.commandPrefix;
  if (!pre) return cmd;
  return `${pre}${cmd}`;
}

function handlePreToolUse(input: any): void {
  if (!isBashTool(input.tool_name)) return;
  const ti = input.tool_input || {};
  let cmd = typeof ti.command === "string" ? ti.command : "";
  cmd = parseCommand(cmd);
  const reason = denyReason(cmd);
  if (reason) {
    console.log(
      JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PreToolUse",
          permissionDecision: "deny",
          permissionDecisionReason: reason,
        },
      }),
    );
    return;
  }
  let next = applyConnection(cmd);
  next = applyPrefix(next);
  if (next === cmd) return;
  const updated = { ...ti, command: next };
  console.log(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "allow",
        permissionDecisionReason: "portal-sandbox: command rewritten",
        updatedInput: updated,
      },
    }),
  );
}

function handleUserPromptSubmit(): void {
  const t = POLICY.userSubmitFragment;
  if (!t) return;
  console.log(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "UserPromptSubmit",
        additionalContext: t,
      },
    }),
  );
}

function handleSessionStart(): void {
  const t = POLICY.sessionFragment;
  if (!t) return;
  console.log(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "SessionStart",
        additionalContext: t,
      },
    }),
  );
}

function gateActive(): boolean {
  const v = process.env[POLICY.gateEnv];
  return v === POLICY.gateValue;
}

function main(): void {
  const raw = fs.readFileSync(0, "utf8");
  if (!raw.trim()) process.exit(0);
  let input: any;
  try {
    input = JSON.parse(raw);
  } catch {
    process.exit(0);
  }
  if (!gateActive()) process.exit(0);
  const ev = input.hook_event_name || input.hookEventName;
  if (ev === "PreToolUse") handlePreToolUse(input);
  else if (ev === "UserPromptSubmit") handleUserPromptSubmit();
  else if (ev === "SessionStart") handleSessionStart();
}

main();
