// Generated by gen-agent-sandbox — do not edit by hand.
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { spawnSync } from "node:child_process";

const POLICY = <<<POLICY_JSON>>>;

function parseCommand(cmd: string): string {
  const argv = POLICY.shellParserArgv;
  if (!argv || argv.length === 0) return cmd;
  const bin = argv[0];
  const args = argv.slice(1);
  const r = spawnSync(bin, args, { input: cmd, encoding: "utf8", maxBuffer: 10 * 1024 * 1024 });
  if (r.status !== 0 || typeof r.stdout !== "string") return cmd;
  const out = r.stdout.trim();
  return out.length > 0 ? out : cmd;
}

function gateActive(): boolean {
  return process.env[POLICY.gateEnv] === POLICY.gateValue;
}

function scriptWrapperDenial(cmd: string): string | null {
  if (!POLICY.scriptWrapperRequired) return null;
  const t = cmd.trimStart();
  for (const p of POLICY.scriptWrapperPrefixes) {
    if (p && t.startsWith(p)) return null;
  }
  return (
    "Denied: shell command must begin with an accepted script-wrapper invocation " +
    "(portal-sandbox). No prefix matched; this check is intentionally shallow and does not parse shell syntax."
  );
}

function denyReason(cmd: string): string | null {
  for (const s of POLICY.denySubstrings) {
    if (s && cmd.includes(s)) return `Denied: command contains blocked substring: ${s}`;
  }
  for (const src of POLICY.denyRegexes) {
    if (!src) continue;
    try {
      const re = new RegExp(src);
      if (re.test(cmd)) return `Denied: command matches blocked pattern: ${src}`;
    } catch {
      continue;
    }
  }
  return null;
}

function applyConnection(cmd: string): string {
  const p = POLICY.connectionScriptPath;
  const triggers = POLICY.connectionScriptTriggers;
  if (!p || triggers.length === 0) return cmd;
  for (const t of triggers) {
    if (t && cmd.includes(t)) return `${p} ${cmd}`;
  }
  return cmd;
}

function applyPrefix(cmd: string): string {
  const pre = POLICY.commandPrefix;
  if (!pre) return cmd;
  return `${pre}${cmd}`;
}

export default function (pi: ExtensionAPI) {
  if (!gateActive()) return;

  pi.on("session_start", async (_event, ctx) => {
    const s = POLICY.sessionFragment;
    if (s) ctx.ui.notify(`[portal-sandbox] ${s.slice(0, 200)}${s.length > 200 ? "…" : ""}`, "info");
  });

  pi.on("before_agent_start", async (event) => {
    const parts: string[] = [];
    if (POLICY.sessionFragment) parts.push(POLICY.sessionFragment);
    if (POLICY.userSubmitFragment) parts.push(POLICY.userSubmitFragment);
    if (parts.length === 0) return {};
    return { systemPrompt: `${event.systemPrompt}\n\n${parts.join("\n\n")}` };
  });

  pi.on("tool_call", async (event) => {
    const tn = event.toolName;
    if (!POLICY.bashToolNames.includes(tn)) return;
    const input = event.input as { command?: string };
    let cmd = typeof input.command === "string" ? input.command : "";
    cmd = parseCommand(cmd);
    const wrapDeny = scriptWrapperDenial(cmd);
    if (wrapDeny) return { block: true, reason: wrapDeny };
    const reason = denyReason(cmd);
    if (reason) return { block: true, reason };
    let next = applyConnection(cmd);
    next = applyPrefix(next);
    if (typeof input.command === "string") {
      input.command = next;
    }
  });
}
